stages:
  - dockerbuild-push

package:
  image: docker:latest
  stage: dockerbuild-push
  services:
      - docker:dind
  before_script:
      - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PW
  script:
      - echo $GITLAB_USER 로 로그인했습니다. 스크립트를 실행합니다.
      - docker build -t registry.gitlab.com/$GITLAB_USER/$PROJECT_NAME . 
      - docker push registry.gitlab.com/$GITLAB_USER/$PROJECT_NAME
  only:
      - sprint1
  after_script:
      - docker logout
